# Site settings
title: Ariun-Erdene Tumurchuluun
description: Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ariun-Erdene Tumurchuluun
user_description: 
user_title: Flowing like water
email: ariunerdene.tn@gmail.com
twitter_username: ariuha_tn
# instagram_username: 
# facebook_username: 
# linkedin_username: 
github_username:  tariunerdene
# medium_username: 
# medium_url: 
# gplus_username:  
cv_url: https://ariunerdenetum.github.io/assets/files/cv_ariunerdene.pdf

exclude: ['package.json', 'src' , 'node_modules']
